version: "3"

tasks:
  test:
    cmds:
      - go test -v -coverprofile=coverage.out ./...
  show-cover:
    cmds:
      - dokimi report --input=coverage.out --output=coverage.json --reporter=istanbul --show
  default:
    cmds:
      - go build ./...
    silent: true
